export const FIELD_NAMES = {
  fullName: "Full name",
  email: "Email",
  address: "Address",
  password: "Password",
  IdConfirmation: "Upload your ID (file upload)",
};

export const FIELD_TYPES = {
  fullName: "text",
  email: "email",
  address: "text",
  password: "password",
};

export const FIELD_PLACEHOLDERS = {
  fullName: "First and last name",
  email: "Your email address",
  address: "Full address and postcode",
  password: "At least 8 characters",
  IdConfirmation: "Upload your ID (file upload)",
};

export const sampleItems = [
  {
    id: 1,
    title: "Cordless Power Drill",
    category: "tools",
    rating: 4.8,
    total_items: 5,
    available_items: 5,
    available: true,
    summary:
      "Compact cordless drill suitable for DIY tasks and light home repairs. Easy to handle and powerful enough for everyday use. Perfect for short-term projects.",
    description:
      "Reliable cordless drill designed for everyday DIY and home improvement tasks. Ideal for assembling furniture, mounting shelves, drilling into wood, and completing light renovation work. The lightweight design makes it comfortable to use, even for beginners. Adjustable speed settings give better control across different materials. Includes batteries, charger, carrying case, and a starter set of drill bits. A practical choice when you only need a drill for a few days.",
    image: "/images/items/cordless-drill.jpg",
    condition: "Excellent",
    included: [
      "Cordless drill",
      "2 rechargeable batteries",
      "Battery charger",
      "Carrying case",
      "Drill bit starter set",
    ],
    brand: "Bosch Cordless Combi Drill EasyImpact 18V-40",
    borrow_duration: 3,
  },
  {
    id: 2,
    title: "Single-Speed City Bike",
    category: "sports",
    rating: 4.9,
    total_items: 2,
    available_items: 2,
    available: true,
    summary:
      "Lightweight city bike perfect for commuting and weekend rides. Easy to handle and comfortable for short journeys. A great alternative to public transport.",
    description:
      "Well-maintained single-speed bicycle designed for urban riding and everyday commuting. The lightweight frame makes it easy to manoeuvre through busy streets while still feeling stable. Ideal for commuting, running errands, or exploring the neighbourhood. Simple single-speed setup keeps the ride low-maintenance and easy to use. Best suited for paved roads and short to medium-distance journeys. Includes basic safety accessories for convenient borrowing.",
    image: "/images/items/bicycle.jpg",
    condition: "Excellent",
    included: ["Bike lock", "Front light", "Rear light"],
    brand: "Fagero Single-Speed Bike",
    borrow_duration: 7,
  },
  {
    id: 3,
    title: "4-Person Camping Tent",
    category: "travel",
    rating: 4.7,
    total_items: 2,
    available_items: 2,
    available: false,
    summary:
      "Spacious tent suitable for camping weekends and festivals. Comfortable for up to four people. Easy to pack and transport.",
    description:
      "Durable camping tent designed for weekend trips, festivals, and family outdoor breaks. The interior comfortably fits up to four people while still leaving space for small bags. Its simple pole system makes setup manageable even for beginner campers. Weather-resistant fabric helps protect against light rain and wind. The tent packs into a carry bag for easier transport by car. Ideal for occasional camping without buying your own full setup.",
    image: "/images/items/camping-tent.jpg",
    condition: "Good",
    included: ["Tent", "Tent poles", "Ground pegs", "Carry bag"],
    brand: "Quechua 4-Person Tent",
    borrow_duration: 14,
  },
  {
    id: 4,
    title: "Pet Travel Carrier",
    category: "pets",
    rating: 4.8,
    total_items: 4,
    available_items: 4,
    available: true,
    summary:
      "Comfortable carrier for small dogs and cats. Great for vet visits, train journeys, and short trips. Lightweight and easy to carry.",
    description:
      "Soft-sided pet carrier designed for safe and comfortable travel with small pets. Breathable mesh panels help with airflow and visibility during journeys. The padded base gives extra comfort for short trips or waiting rooms. It is useful for vet appointments, train travel, taxi rides, or temporary pet transport. The carrier folds down more easily than rigid crates when not in use. Best suited for small dogs, cats, and similar-sized pets.",
    image: "/images/items/dog-carrier.jpg",
    condition: "Excellent",
    included: ["Pet carrier", "Removable padded mat"],
    brand: "Portable Soft-Sided Pet Carrier",
    borrow_duration: 14,
  },
  {
    id: 5,
    title: "Dyson Cordless Vacuum",
    category: "electronics",
    rating: 4.9,
    total_items: 6,
    available_items: 6,
    available: true,
    summary:
      "Powerful cordless vacuum cleaner for quick home cleaning. Lightweight and easy to move around furniture. Especially useful for pet hair and dust.",
    description:
      "High-performance Dyson cordless vacuum designed to make cleaning fast and convenient. Strong suction helps remove dust, dirt, and pet hair from carpets, hard floors, and upholstery. The cordless design makes it easy to move between rooms without changing plug sockets. Multiple attachments help with corners, stairs, and furniture. It is ideal for occasional deep cleans, end-of-tenancy preparation, or quick household maintenance. A useful option when you need a premium vacuum for a short time.",
    image: "/images/items/dyson.jpg",
    condition: "Excellent",
    included: ["Vacuum", "Charging dock", "Crevice tool", "Brush attachment"],
    brand: "Dyson V8 Animal",
    borrow_duration: 2,
  },
  {
    id: 6,
    title: "Pet Grooming Kit",
    category: "pets",
    rating: 4.6,
    total_items: 2,
    available_items: 2,
    available: true,
    summary:
      "Handy grooming kit for trimming and tidying pets at home. Suitable for small touch-ups between professional appointments. Easy to borrow for occasional use.",
    description:
      "Practical pet grooming kit for keeping dogs neat between salon visits. Includes basic tools for trimming, combing, and maintaining longer coats. Best suited for light grooming, tidy-ups, and small corrections rather than full professional cuts. The compact set is easy to store and transport. Useful for pet owners who only need grooming tools occasionally. Please clean all tools before returning them.",
    image: "/images/items/grooming-kit.jpg",
    condition: "Good",
    included: ["Grooming scissors", "Comb", "Cleaning cloth", "Storage pouch"],
    brand: "Professional Pet Grooming Set",
    borrow_duration: 2,
  },
  {
    id: 7,
    title: "Home Cinema Projector",
    category: "electronics",
    rating: 4.8,
    total_items: 3,
    available_items: 3,
    available: true,
    summary:
      "Compact projector for movie nights, gaming, and presentations. Produces a large screen experience at home. Simple to set up for special occasions.",
    description:
      "Full HD home cinema projector designed for films, games, sports, and casual presentations. It creates a large image that works especially well in darker rooms. HDMI support makes it easy to connect laptops, consoles, and streaming devices. The compact design means it can be moved between rooms or taken to gatherings. Built-in speakers are useful for quick setup, though external speakers can improve the experience. Great for hosting without buying expensive entertainment equipment.",
    image: "/images/items/home-cinema-projector.jpg",
    condition: "Excellent",
    included: ["Projector", "Power cable", "Remote control", "HDMI cable"],
    brand: "Valerion Home Cinema Projector",
    borrow_duration: 4,
  },
  {
    id: 8,
    title: "Aluminium Step Ladder",
    category: "tools",
    rating: 4.7,
    total_items: 5,
    available_items: 5,
    available: true,
    summary:
      "Compact step ladder for decorating, cleaning, and household tasks. Stable and easy to move around. Ideal when you only need extra height temporarily.",
    description:
      "Durable aluminium step ladder suitable for everyday household and DIY tasks. It is useful for painting, changing light bulbs, cleaning high shelves, or reaching storage spaces. The wide steps provide better stability than a small stool. Anti-slip feet help keep it secure on suitable flat surfaces. Its folding design makes it easier to carry and store. A practical item to borrow rather than buy for occasional use.",
    image: "/images/items/ladder.jpg",
    condition: "Good",
    included: ["Step ladder"],
    brand: "Krause Aluminium Step Ladder",
    borrow_duration: 2,
  },
  {
    id: 9,
    title: "LEGO Building Box",
    category: "kids",
    rating: 4.9,
    total_items: 5,
    available_items: 5,
    available: true,
    summary:
      "Large collection of LEGO bricks for creative building. Great for children, families, and relaxed screen-free play. Provides hours of imaginative entertainment.",
    description:
      "Mixed LEGO building box with a variety of bricks, wheels, connectors, and colourful pieces. Perfect for open-ended play, creative challenges, and family building sessions. Children can use it to create vehicles, houses, characters, or completely original designs. It is also enjoyable for adults who want a relaxing hands-on activity. The pieces come in a storage box for easier transport and cleanup. Great for weekends, playdates, or school holiday activities.",
    image: "/images/items/lego.jpg",
    condition: "Good",
    included: ["Mixed LEGO pieces", "Storage box"],
    brand: "LEGO Classic Collection",
    borrow_duration: 14,
  },
  {
    id: 10,
    title: "Picnic Blanket",
    category: "travel",
    rating: 4.5,
    total_items: 10,
    available_items: 10,
    available: true,
    summary:
      "Soft picnic blanket for parks, beaches, and outdoor plans. Easy to roll up and carry. Great for sunny days and relaxed gatherings.",
    description:
      "Large picnic blanket designed for comfortable outdoor use in parks, gardens, and beaches. The soft top layer makes it pleasant to sit on for longer periods. A practical backing helps protect against slightly damp grass or uneven ground. It rolls up neatly with carrying straps, making transport simple. Ideal for picnics, outdoor cinema evenings, beach trips, and family days out. Easy to borrow for one-day plans without storing one at home.",
    image: "/images/items/picnic-blanket.jpg",
    condition: "Excellent",
    included: ["Picnic blanket", "Carrying straps"],
    brand: "Outdoor Roll-Up Picnic Blanket",
    borrow_duration: 2,
  },
  {
    id: 11,
    title: "Polaroid Instant Camera",
    category: "electronics",
    rating: 4.8,
    total_items: 3,
    available_items: 3,
    available: false,
    summary:
      "Instant camera for parties, events, and creative photos. Prints memories straight away. A fun choice for birthdays and gatherings.",
    description:
      "Polaroid instant camera designed for capturing moments and printing them immediately. It is great for birthdays, parties, trips, weddings, and creative projects. The simple point-and-shoot design makes it easy for guests to use. Instant photos add a nostalgic and personal touch to events. Borrowers should bring their own compatible film unless agreed with the owner. A fun item to use occasionally without buying a camera yourself.",
    image: "/images/items/polaroid.jpg",
    condition: "Excellent",
    included: ["Instant camera", "Carrying strap"],
    brand: "Polaroid Now+",
    borrow_duration: 3,
  },
  {
    id: 12,
    title: "Sewing Machine",
    category: "crafts",
    rating: 4.8,
    total_items: 2,
    available_items: 2,
    available: false,
    summary:
      "Beginner-friendly sewing machine for repairs and creative projects. Useful for clothing alterations, crafts, and small home tasks. Simple enough for occasional use.",
    description:
      "Reliable sewing machine suitable for clothing repairs, alterations, and hobby projects. It can be used for hemming trousers, fixing seams, making simple crafts, or experimenting with sewing. The controls are straightforward, making it approachable for beginners. It also offers enough basic stitch options for more confident users. Compact size makes it easier to transport and set up on a table. A practical choice if you need a machine for a short project.",
    image: "/images/items/sewing-machine.jpg",
    condition: "Excellent",
    included: ["Sewing machine", "Power cable", "Starter thread kit"],
    brand: "Brother Sewing Machine",
    borrow_duration: 5,
  },
  {
    id: 13,
    title: "Spikeball Set",
    category: "sports",
    rating: 4.9,
    total_items: 3,
    available_items: 3,
    available: true,
    summary:
      "Fast-paced outdoor game for parks, beaches, and garden parties. Easy to learn and fun in groups. Great for active weekends.",
    description:
      "Complete Spikeball set for energetic outdoor games with friends or family. The game is quick to set up and works well on grass, sand, or other flat outdoor spaces. It is ideal for beach days, picnics, garden parties, and casual sports sessions. Rules are simple enough for beginners while still being competitive for regular players. The carry bag makes it easy to transport. A fun item to borrow for one-off gatherings or sunny weekends.",
    image: "/images/items/spikeball.jpg",
    condition: "Excellent",
    included: ["Net", "3 balls", "Carry bag"],
    brand: "Spikeball Pro",
    borrow_duration: 2,
  },
  {
    id: 14,
    title: "Woody Action Figure",
    category: "kids",
    rating: 4.7,
    total_items: 2,
    available_items: 2,
    available: true,
    summary:
      "Toy Story Woody figure for imaginative play. Great for children who enjoy character-based stories. Also suitable as a temporary collectible display.",
    description:
      "Detailed Woody action figure inspired by Toy Story. The articulated design makes it suitable for imaginative play and storytelling. Children can use it alongside other toys for role-play, adventures, and pretend scenes. It is also a nice option for themed parties, decorations, or short-term display. Best borrowed by families who want variety without buying more toys permanently. Please return with all removable parts included.",
    image: "/images/items/toy-story-woody.jpg",
    condition: "Good",
    included: ["Woody action figure"],
    brand: "Disney Pixar Toy Story",
    borrow_duration: 14,
  },
  {
    id: 15,
    title: "UNO Card Game",
    category: "kids",
    rating: 4.9,
    total_items: 5,
    available_items: 5,
    available: true,
    summary:
      "Classic card game for family nights and casual gatherings. Easy to learn and suitable for most ages. Small enough to take anywhere.",
    description:
      "UNO is a classic family card game that is quick to learn and easy to play. It works well for relaxed evenings, parties, holidays, and travel entertainment. The game is suitable for children and adults, making it a reliable choice for mixed-age groups. Rounds are usually fast, so it is easy to play casually without a long setup. The compact deck is simple to transport and store. A great low-effort option for borrowing when hosting guests.",
    image: "/images/items/uno.jpg",
    condition: "Excellent",
    included: ["UNO deck", "Game instructions"],
    brand: "Mattel UNO",
    borrow_duration: 3,
  },
  {
    id: 16,
    title: "Professional Waffle Maker super puper",
    category: "kitchen",
    rating: 4.8,
    total_items: 2,
    available_items: 2,
    available: true,
    summary:
      "Waffle maker for brunches, breakfasts, and weekend treats. Makes crisp golden waffles at home. Great for hosting without buying another appliance.",
    description:
      "Professional-style waffle maker designed for easy homemade waffles. The non-stick plates help create crisp waffles with less mess and easier cleanup. It is ideal for brunches, birthdays, family breakfasts, or cosy weekend plans. Adjustable heating gives better control over texture and browning. The appliance is simple to use and does not need much setup. Perfect for occasional use when you want something special without storing another kitchen gadget.",
    image: "/images/items/waffle-maker.jpg",
    condition: "Excellent",
    included: ["Waffle maker", "User guide"],
    brand: "Cooks Professional Waffle Maker",
    borrow_duration: 2,
  },
];
